---
title: Tidy Tuesday
author: Ingrid Zoll
date: '2021-03-18'
slug: tidy-tuesday-march-16
categories: []
tags: [RStudio, tidytuesday]
subtitle: ''
summary: ''
authors: []
lastmod: '2021-03-18T11:59:19-07:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, message=FALSE, warning=FALSE}
library(tidyverse)
library(lubridate)
library(ggdark)
library(wesanderson)
conflicted::conflict_prefer("filter", "dplyr")
```

```{r loading data, message=FALSE, warning=FALSE, results='hide'}
# Get the Data
games <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-03-16/games.csv')
```

```{r by month popularity, message=FALSE, warning=FALSE}
mostpop_bymonth <- games %>%
  unite(yearmonth, month:year)%>%
  mutate(date = my(yearmonth)) %>%
  group_by(date)%>% 
  top_n(3, avg) %>% 
  ungroup %>%
  add_count(gamename, name = "count") %>%
  mutate(label = gamename, label = case_when(
    count < 10 ~ "Other games",
    count > 10 ~ gamename)) %>%
  mutate(game = factor(label), game = fct_infreq(label)) %>%
  mutate(game = str_replace(game, "PLAYERUNKNOWN'S BATTLEGROUNDS", "PUBG"), 
         game = str_replace(game, "Counter-Strike: Global Offensive", "CS GO"))
```

```{r}
ggplot(mostpop_bymonth, aes(x=date, y=avg, color=game))+
  geom_line()+
  scale_color_manual(values = wes_palette("Zissou1"))+
  dark_theme_gray() +
  labs(caption = "PUBG = PlayerUnknown's BattleGround \nCS GO = Counter-Strike: Global Offensive",
       title= "The Three Most Popular Games on Steam by Month", 
       y="Average number of players at the same time", x="Date")
```

```{r, message=FALSE, warning=FALSE}
populargames <- mostpop_bymonth %>%
  filter(game == "CS GO" | game == "PUBG"| game == "Dota 2")
```

```{r}
ggplot(populargames, aes(x=date, y=avg))+
  dark_theme_gray()+
  scale_color_manual(name = 'Game', values =c('CS GO'="#F21A00",'Dota 2'="#EBCC2A", 'PUBG' = "#3B9AB2"),
        labels = c("CS GO", "Dota 2", "PUBG"))+
  geom_linerange(aes(ymax=peak, ymin=avg, color=game), size=.25)+
  geom_point(aes(y=peak, color=game), size=.7)+
  geom_point(aes(y=avg, color=game), size=.7)+
  labs(title="Three Most Popular Games", x="Date", y="Number of players")
```

