---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Reproducible Research: A Talk on How to Do the Same Thing More Than Once

Computational reproducibility is the ability to obtain identical results from the same data with the same computer code.
The high rate of irreproducible research limits the reach of results and decreases the efficiency of researchers.
Reproducible research is a building block for transparent and cumulative science because it enables the originator and other researchers, on other computers and later in time, to reproduce and thus understand how results came about.
In this talk, I present a conceptual analysis of what it takes to work reproducible, provide hints on how to work reproducible in practice, and what problems researchers are likely to encounter.

# Reproducible Research in R: A Workshop on How to Do the Same Thing More Than Once

Many researchers want to work reproducibly, but it is not easy.
Considerable time is required to acquire the skills required for reproducible research, and the path is lined with pitfalls.
This workshop gets researchers up to speed on how to create reproducible data analyses in R (and beyond).
Specifically, researchers learn to automate the whole process from raw data to publishable manuscripts.
This automation is possible by combining dynamic document generation (via R Markdown), version control (via Git), workflow orchestration (via Make) and software management (via Docker).
The resulting workflow is highly transferable across machines and time.
These core properties of reproducibility are demonstrated for any reader by automatically reproducing the manuscript online.
These tools and, therefore, automatic reproduction of results are available on any machine with Docker installed.
Docker is supported on online cloud services, e.g. GitHub Actions, which are used to "proof" reproducibility to the public.
In short, after the workshop, researchers can work reproducibly and hence be confident in their results.
*Note: The workshop teaches the concepts put forward in the talk with the same title.*
